version: 2
updates:
  #Golang
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  # React
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"